CREATE TABLE "DataProtectionKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" text,
    "Xml" text,
    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);


CREATE TABLE "History" (
    "HistoryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PostId" integer NOT NULL,
    "ActionType" text,
    CONSTRAINT "PK_History" PRIMARY KEY ("HistoryId")
);


CREATE TABLE "Mission" (
    "MissionId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Description" text NOT NULL,
    "IsCompleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Mission" PRIMARY KEY ("MissionId")
);


CREATE TABLE "Notification" (
    "NotificationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "TriggerId" integer NOT NULL,
    "PostId" integer NOT NULL,
    "Type" text NOT NULL,
    "Message" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notification" PRIMARY KEY ("NotificationId")
);


CREATE TABLE "Post" (
    "PostId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Title" text NOT NULL,
    "Location" text,
    "EventDateTime" timestamp with time zone NOT NULL,
    "Description" text NOT NULL,
    "SportType" text NOT NULL,
    "CreateDate" timestamp with time zone NOT NULL,
    "MaxPeople" integer NOT NULL,
    "ImageUrl" text,
    "Status" text,
    "Lat" double precision,
    "Lon" double precision,
    CONSTRAINT "PK_Post" PRIMARY KEY ("PostId")
);


CREATE TABLE "User" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Password_hash" text NOT NULL,
    "Email" text NOT NULL,
    "ProfileUrl" text,
    "Info" text,
    CONSTRAINT "PK_User" PRIMARY KEY ("UserId")
);


CREATE TABLE "Comment" (
    "CommentId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PostId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Text" text,
    CONSTRAINT "PK_Comment" PRIMARY KEY ("CommentId"),
    CONSTRAINT "FK_Comment_Post_PostId" FOREIGN KEY ("PostId") REFERENCES "Post" ("PostId") ON DELETE CASCADE
);


CREATE TABLE "Member" (
    "PostId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Status" text,
    "JoinedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Member" PRIMARY KEY ("PostId", "UserId"),
    CONSTRAINT "FK_Member_Post_PostId" FOREIGN KEY ("PostId") REFERENCES "Post" ("PostId") ON DELETE CASCADE
);


CREATE INDEX "IX_Comment_PostId" ON "Comment" ("PostId");




-- Supabase exposes the public schema over its REST API with the public anon key.
-- This app talks to Postgres directly, so shut that door: no RLS policies = no rows for anon/authenticated.
ALTER TABLE "DataProtectionKeys" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "History" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Mission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Post" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Comment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Member" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
-- The "Session" table is created by the app on first start; this covers it too.
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
